language: java

jdk:
  - oraclejdk8

env:  
  global:  
    - TERM=dumb

before_install:
  - sudo apt-get update
  - sudo pip install codecov
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
      
script: gradle -b training/build.gradle check jacocoTestReport jar

after_success: codecov
